### PR TITLE
Fix activation

### PR DESCRIPTION
**Pull request by Randl**
Should fix https://github.com/openai/mujoco-py/issues/66 https://github.com/openai/mujoco-py/issues/99 https://github.com/openai/mujoco-py/issues/103
As mentioned in https://github.com/openai/mujoco-py/issues/103 , for some reason `exec_module` calls for `builder.py` twice, and `mj_activate` fails on the second one. Not sure if it is valid workaround though.

### CODE REVIEW

**Comment by Randl** [comment]
I successfully installed it with `pip3 install git+https://github.com/Randl/mujoco-py.git@activation_fix --user` so I believe it works

**Comment by Randl** [comment]
ping @siemanko @wojzaremba @machinaut

**Comment by wojzaremba** [comment]
Could you bump version, please. I will accept it.

**Comment by Randl** [comment]
@wojzaremba What do you mean? The branch appears to have no conflicts with master

**Comment by Randl** [comment]
@wojzaremba you mean here: https://github.com/openai/mujoco-py/blob/master/mujoco_py/version.py#L3 
to 1.52.1.43?

**Comment by Randl** [comment]
ping @wojzaremba

**Comment by wojzaremba** [comment]
Could you check if it works for you with version  1.50.1.53 @Randl

**Comment by Randl** [comment]
Yes it works. Thanks.

**Pull request closed without merging**
