### PR TITLE
Programmatically determine directory containing ` libOpenGL.so` and `libEGL.so`

### PR DESCRIPTION
**Pull request by lobachevzky**
Currently the path to the directory for these files is hard-coded. Moreover, this path does not actually work on several of the machines that I have tried to use it with. As a result the install command silently fails to utilize the GPU. In general, these files appear to be located under `/usr/lib/nvidia-<version>/`. This script programmatically determines the version of nvidia and then checks whether either the original directory or this directory exist.

### CODE REVIEW

**Comment by lobachevzky** [comment]
I'm a little new to working with Travis so I'm hoping you can help me with this. I can't figure out how to reproduce the command that failed on my end (`curl $MUJOCO_FOR_LINUX | tar -xz ./mjkey.txt`) since that variable is not defined in my environment and I don't know what value it is being assigned.

**Comment by machinaut** [comment]
This looks good to me, not sure why travis is failing.  Hit the retry button to see if it was a fluke.

**Comment by machinaut** [comment]
Well at least the failure is consistent.

**Comment by machinaut** [comment]
I think travis isn't liking this because its coming from an external repo.  I'm going to try re-pushing this as a branch directly on this repo to see if it likes that.

**Comment by machinaut** [comment]
Verified that the failing test (travis-ci/pr) passes when pushed to this repo.

**Comment by lobachevzky** [comment]
Great! Thanks for your help. Is there anything else I need to do? I'm also a little new to pull requests.

**Comment by lobachevzky** [comment]
Gentlemen, I finally got around to installing my NVIDIA drivers with the `--install-libglvnd` flag and lo and behold, `libOpenGL.so.0` and `libEGL.so.1` ended up in `/usr/lib/x86_64-linux-gnu/` which is already on gcc's search path. Consequently, you get an error at line 249. This would have been an issue in the previous version as well, but I'm wondering if there's a principled way to locate these shared object libraries.

**Pull request merged**
